[package]
name = "wasmtime-cabish"
version = "0.6.0"
description = "Wasmtime cabish integration"

authors.workspace = true
categories.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
anyhow = { workspace = true }
cabish = { workspace = true }
tracing = { workspace = true, features = ["attributes"] }
wasmtime = { workspace = true, features = ["component-model", "runtime"] }
